version: 1.0.0.{build}
image: Visual Studio 2017

# prevent the double build when a branch has an active PR
skip_branch_with_pr: true

install:
  - choco install gitversion.portable -pre -y

before_build:
  - git submodule -q update --init
  - cmd: dotnet --version
  - ps: c:\ProgramData\chocolatey\lib\gitversion.portable\tools\gitversion.exe /l console /output buildserver

build_script:
- cmd: build.cmd

test_script:
- tests\CodeCoverage\CodeCoverage.cmd

after_test:
  - cmd: appveyor PushArtifact "artifacts\SixLabors.ImageSharp.Web.%GitVersion_NuGetVersion%.nupkg"

deploy:
    # MyGet Deployment for builds & releases
 - provider: NuGet
   server: https://www.myget.org/F/imagesharp/api/v2/package
   symbol_server: https://www.myget.org/F/imagesharp/symbols/api/v2/package
   api_key:
     secure: fz0rUrt3B1HczUC1ZehwVsrFSWX9WZGDQoueDztLte9/+yQG+BBU7UrO+coE8lUf
   artifact: /.*\.nupkg/
   on:
     branch: master
